### ISSUE TITLE
Iron Fist Status Screen

### ISSUE THREAD

**Issue by Jeri232** [Machir/IronFist#12]
Idea:
Make the Iron fist icon a clickable and when you were to click on it will open up this:
 Current Fist Lvl:X
 More Blocks to Punch Until Next Lvl: X
 Blocks Punchable: Sponge
 Blocks Unpunchable: Sand

(stuff like that)

Point:

The status screen should be able to give you more information about your level.

**Comment by Machir** [comment]
I think I'll put this on a hold, blocks left to punch is depending on hardness. The fist icon shows progress in a not so detailed way but adding a GUI just for that seems useless. The level is also shown on the fist itself already so that's known too. Punchable and unpunchable blocks are depending on tool levels which are equal to your fist level so that's not needed either. I'd add a GUI if there was more use to it, maybe I'll check out WAILA and made something like WAILA harvestability to show if a block is punchable or an addition to harvestability if that's possible.
